stages:
  - deploy

variables:
  DB_NAME: ${DB_NAME}
  DB_USER: ${DB_USER}
  DB_PASSWORD: ${DB_PASSWORD}
  JPA_DDL_AUTO: ${JPA_DDL_AUTO}
  MYSQL_DATABASE: ${MYSQL_DATABASE}
  MYSQL_USERNAME: ${MYSQL_USERNAME}
  MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

deploy:
  stage: deploy
  tags:
    - ballog
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - |
      ssh -i ~/.ssh/id_rsa ubuntu@$SERVER_IP "
        cd /home/ubuntu/S12P31A404 && 
        git fetch &&
        git checkout $CI_COMMIT_REF_NAME &&
        git pull &&
        
        # 환경 변수 파일 생성
        echo \"DB_NAME=${DB_NAME}\" > .env &&
        echo \"DB_USER=${DB_USER}\" >> .env &&
        echo \"DB_PASSWORD=${DB_PASSWORD}\" >> .env &&
        echo \"JPA_DDL_AUTO=${JPA_DDL_AUTO}\" >> .env &&
        echo \"MYSQL_DATABASE=${MYSQL_DATABASE}\" >> .env &&
        echo \"MYSQL_USERNAME=${MYSQL_USERNAME}\" >> .env &&
        echo \"MYSQL_PASSWORD=${MYSQL_PASSWORD}\" >> .env &&
        echo \"MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}\" >> .env &&
        
        # 백엔드 서비스 재빌드 및 배포
        echo \"$CI_COMMIT_REF_NAME 브랜치: 백엔드 서비스 빌드 및 배포 중...\" &&
        docker-compose down backend &&
        docker-compose build backend &&
        docker-compose up -d backend
      "
  only:
    - dev/be