spring:
  config:
    import: classpath:/env.yml
  application:
    name: ballog
  jackson:
    property-naming-strategy: SNAKE_CASE

  datasource:
    postgres:
      url: ${DB_URL}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      driver-class-name: org.postgresql.Driver
      hikari:
        max-lifetime: 60000
    
    mysql:
      url: ${MYSQL_DB_URL}
      username: ${MYSQL_USERNAME}
      password: ${MYSQL_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        max-lifetime: 60000

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO}
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}



